id: P008189
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:06:56.565561
source_metadata:
  id: bdr:W1AC434
  title: 'སོ་ནམ་པ། '
  author: ''
  volumes:
    6ef535f970664d10ad8903c056235437:
      image_group_id: I2PD18766
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
