id: P008189
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC434
  title: 'སོ་ནམ་པ། '
  author: ''
  volumes:
    6ef535f970664d10ad8903c056235437:
      image_group_id: I2PD18766
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
